name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Backend Docker images
      - name: Build Backend Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/collection:latest .

      # Step 5: Push Backend Docker images
      - name: Push Backend Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/collection:latest
